version: '3.3'
services:
  mongodb:
    image : mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 24017:27017
    restart: always
  application:
    container_name: nestjs_api
    image: nestjs-api:1.0.0
    build: .
    ports:
      - "$PORT:$PORT"
    depends_on:
      - mongodb
    restart: unless-stopped
    env_file:
      - .env